module.exports = {
  transferUpdatesParser: require('./transferUpdatesParser'),
  postWithObjectParser: require('./postWithObjectParser'),
  createObjectParser: require('./createObjectParser'),
  appendObjectParser: require('./appendObjectParser'),
  followObjectParser: require('./followObjectParser'),
  guestCommentParser: require('./guestCommentParser'),
  claimRewardParser: require('./claimRewardParser'),
  witnessVoteParser: require('./witnessVoteParser'),
  customJsonParser: require('./customJsonParser'),
  objectTypeParser: require('./objectTypeParser'),
  transferParser: require('./transferParser'),
  withdrawParser: require('./withdrawParser'),
  recoveryParser: require('./recoveryParser'),
  commentParser: require('./commentParser'),
  userParsers: require('./userParsers'),
  voteParser: require('./voteParser'),
  mainParser: require('./mainParser'),
};
