module.exports = {
  ObjectFactory: require('./Object/ObjectFactory'),
  ObjectTypeFactory: require('./ObjectType/ObjectTypeFactory'),
  UserFactory: require('./User/UserFactory'),
  PostFactory: require('./Post/postFactory'),
  CommentFactory: require('./Comment/commentFactory'),
  VoteFactory: require('./Vote/VoteFactory'),
  AppendObject: require('./AppendObject/AppendObjectFactory'),
  AppFactory: require('./App/AppFactory'),
  userWobjectFactory: require('./UserWobject/UserWobjectFactory'),
  SubscriptionsFactory: require('./Subscriptions/SubscriptionsFactory'),
  WobjectSubscriptionsFactory: require('./WobjectSubscriptions/WobjectSubscriptionsFactory'),
  CampaignFactory: require('./Campaign/CampaignFactory'),
  WebsitePaymentsFactory: require('./WebsiteTransfers/WebsiteTransfersFactory'),
  WebsiteRefundsFactory: require('./WebsiteRefunds/WebsiteRefundsFactory'),
  RelatedFactory: require('./Related/RelatedFactory'),
  PaymentHistoryFactory: require('./PaymentHistory/PaymentHistoryFactory'),
  HiddenPostsFactory: require('./HiddenPosts/HiddenPostsFactory'),
  HiddenCommentFactory: require('./HiddenComment/HiddenCommentFactory'),
  MutedUsersFactory: require('./MutedUsers/MutedUsersFactory'),
  DepartmentFactory: require('./Department/DepartmentFactory'),
};
