module.exports = {
  Wobj: require('./wObjectModel'),
  User: require('./UserModel'),
  Post: require('./PostModel'),
  ObjectType: require('./ObjectTypeModel'),
  App: require('./AppModel'),
  CommentRef: require('./CommentRef'),
  CommentModel: require('./CommentModel'),
  UserWobjects: require('./UserWobjectsModel'),
  Subscriptions: require('./SubscriptionModel'),
  BellNotifications: require('./BellNotificationsModel'),
  Campaign: require('./CampaignModel'),
  paymentHistoriesModel: require('./PaymentHistoriesModel'),
  wobjectSubscriptions: require('./wobjectSubscriptionModel'),
};
