module.exports = {
  Wobj: require('./wObjectModel'),
  User: require('./UserModel'),
  Post: require('./PostModel'),
  ObjectType: require('./ObjectTypeModel'),
  App: require('./AppModel'),
  CommentRef: require('./CommentRef'),
  CommentModel: require('./CommentModel'),
  UserWobjects: require('./UserWobjectsModel'),
  Subscriptions: require('./SubscriptionModel'),
  Campaign: require('./CampaignModel'),
  paymentHistoriesModel: require('./PaymentHistoriesModel'),
  wobjectSubscriptions: require('./wobjectSubscriptionModel'),
  websitePayments: require('./websitesPaymentsModel'),
  websiteRefunds: require('./websitesRefundsModel'),
  relatedAlbum: require('./relatedAlbumModel'),
  hiddenPostModel: require('./hiddenPostModel'),
  hiddenCommentModel: require('./hiddenCommentModel'),
  mutedUserModel: require('./mutedUserModel'),
  engineDepositModel: require('./engineDepositModel'),
};
